name: CI Build for Docker Action
on:
  push:
    branches: [ main ]
    paths: [ my-docker-action/** ]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Run my own container action
        id: my-docker-action
        uses: ./my-docker-action
        with:
          who-to-greet: 'Harald'

      - name: Output time set in the container
        run: echo "The time was ${{ steps.hello-action.outputs.time }} when the action said hello"
